server:
  port: 8080

spring:
  application:
    name: cat
  datasource:
    username: 'PostgreSQL 14'
    url: jdbc:postgresql://localhost:5432/Cats
    password: '1234'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: create-drop
      show-sql: 'true'

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    cat: cat.queue
  routing-keys:
    internal-notification: internal.notification.routing-key